### ISSUE TITLE
opening up the normalized_car_features file

### ISSUE THREAD

**Issue by yikkin** [theflofly/dnn_from_scratch_py#1]
Hey Florian ,

I m trying to run your code , and I m stumbling over this : 
"    x = list(reader)

Error: iterator should return strings, not bytes (did you open the file in text mode?) "

and it would cool if you could help me out , maybe with the format at which i should register the file to make it work..

**Comment by theflofly** [comment]
Hi,

It is because you are using python 3. I made a commit, can you test with the latest version on master ? It should work.

**Comment by yikkin** [comment]
Yeap , it will work i try that solution before seeing your answer and it work just fine , 
there is some other correction you should bring for those who used python 3 
example for the 'np.array(x).astype(..)'  you should put str rather than "string" and float rather than "flaot"

(but i just check your code and you did it good on your part , man..)

thx , i  will come back to you if i got any issue ;)
